#!/usr/bin/env bash
###############################################################################
# provision_customer.sh — scaffold a new single-tenant Invenzo instance.
#
# Invenzo is single-tenant: one running stack == one business, with its own
# database and its own subdomain. This script generates everything a new
# customer instance needs so onboarding is copy-paste:
#
#   customers/<slug>/.env               — production env with fresh secrets
#   customers/<slug>/docker-compose.override.yml
#                                        — unique project name + host ports so
#                                          multiple instances can share one box
#   customers/<slug>/Caddyfile.snippet  — the vhost block to add to /etc/caddy/Caddyfile
#   customers/<slug>/README.md          — the exact commands to bring it up
#
# It does NOT start anything or touch DNS/Caddy — it only writes files you then
# review and apply. Secrets are written to the per-customer .env only, which is
# gitignored.
#
# Usage:
#   scripts/provision_customer.sh <slug> <domain> [smtp_host] [smtp_from_email]
#
# Example (subdomain-per-customer under a product domain):
#   scripts/provision_customer.sh bro invenzo.app smtp.brevo.com no-reply@invenzo.app
#     -> instance served at https://bro.invenzo.app
#
# Arguments:
#   slug              short customer id, DNS-safe (a-z, 0-9, hyphen). Becomes the
#                     subdomain label and the compose project name.
#   domain            the product apex domain you own (e.g. invenzo.app).
#                     The instance is served at <slug>.<domain>.
#   smtp_host         (optional) SMTP server for password-reset emails.
#   smtp_from_email   (optional) From address for those emails.
#
# If SMTP args are omitted, placeholders are written so the stack still boots;
# password-reset EMAILS will not send until real SMTP values are set (the
# admin-driven password reset in Settings works regardless).
###############################################################################
set -euo pipefail

# --- args -------------------------------------------------------------------
SLUG="${1:-}"
DOMAIN="${2:-}"
# SMTP host defaults to Brevo's free relay (smtp-relay.brevo.com). Override with
# arg 3 only if you use a different provider (e.g. smtp.resend.com).
SMTP_HOST="${3:-smtp-relay.brevo.com}"
SMTP_FROM_EMAIL="${4:-no-reply@${DOMAIN:-example.com}}"

if [ -z "$SLUG" ] || [ -z "$DOMAIN" ]; then
    echo "Usage: $0 <slug> <domain> [smtp_host] [smtp_from_email]" >&2
    echo "Example: $0 bro invenzo.app smtp.brevo.com no-reply@invenzo.app" >&2
    exit 1
fi

# Validate the slug is DNS/label safe (lowercase letters, digits, hyphen; not
# starting/ending with a hyphen). This becomes a subdomain and a project name.
if ! printf '%s' "$SLUG" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
    echo "ERROR: slug '$SLUG' must be lowercase letters, digits, and hyphens (DNS-safe)." >&2
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="${REPO_ROOT}/customers/${SLUG}"
FQDN="${SLUG}.${DOMAIN}"

if [ -e "$OUT_DIR" ]; then
    echo "ERROR: ${OUT_DIR} already exists. Refusing to overwrite an existing customer." >&2
    echo "Delete it manually if you really intend to re-provision (this destroys its generated secrets)." >&2
    exit 1
fi

# --- host port assignment ---------------------------------------------------
# Each instance publishes backend+frontend on unique loopback ports so several
# instances can coexist on one VPS behind a single Caddy. Derive a stable,
# collision-resistant base port from the slug hash, in the 21000-21998 range.
hash_hex="$(printf '%s' "$SLUG" | cksum | cut -d' ' -f1)"
offset=$(( hash_hex % 500 * 2 ))
BACKEND_PORT=$(( 21000 + offset ))
FRONTEND_PORT=$(( 21001 + offset ))

# --- secret generation ------------------------------------------------------
gen() { python3 -c "import secrets,sys; print(secrets.token_urlsafe(int(sys.argv[1])))" "$1"; }
SECRET_KEY="$(gen 48)"
POSTGRES_PASSWORD="$(gen 24)"
REDIS_PASSWORD="$(gen 24)"

mkdir -p "$OUT_DIR"

# --- .env -------------------------------------------------------------------
cat > "${OUT_DIR}/.env" <<EOF
# =============================================================================
# Invenzo production env for customer: ${SLUG}  (${FQDN})
# Generated by scripts/provision_customer.sh. Contains real secrets — never commit.
# =============================================================================
ENVIRONMENT=production

# --- PostgreSQL ---
POSTGRES_USER=invenzo
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=invenzo

# --- Redis (required in production) ---
REDIS_PASSWORD=${REDIS_PASSWORD}

# --- Backend / JWT ---
SECRET_KEY=${SECRET_KEY}

# --- URLs (same-domain layout: frontend at root, API under /api/v1) ---
CORS_ORIGINS=https://${FQDN}
FRONTEND_BASE_URL=https://${FQDN}
NEXT_PUBLIC_API_URL=https://${FQDN}/api/v1
REFRESH_COOKIE_SAMESITE=strict

# --- Unique host ports so multiple instances share one VPS behind Caddy ---
BACKEND_BIND_ADDR=127.0.0.1
FRONTEND_BIND_ADDR=127.0.0.1
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}

# --- SMTP (required to boot; needed for password-reset EMAILS) ---
# Defaults are Brevo's free relay. From Brevo -> Settings -> SMTP & API -> SMTP:
#   SMTP_USERNAME = the "Login" shown there (e.g. 1a2b3c001@smtp-brevo.com)
#   SMTP_PASSWORD = the value from "Generate SMTP key" (NOT your account password)
# SMTP_FROM_EMAIL must be a sender/domain you verified in Brevo, or mail bounces.
# (Admin-driven password reset in Settings works even if these stay blank.)
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
SMTP_USE_TLS=true
EOF

# --- compose override -------------------------------------------------------
# Two isolation problems on a shared box:
#  1. container_name is hardcoded in docker-compose.production.yml, so two
#     instances would collide. The Compose `!reset null` tag removes the
#     hardcoded name so Compose auto-names containers <project>-<service>-N,
#     which is unique per project. (A plain `null` does NOT override a set
#     value in the base file; `!reset` is the documented mechanism.)
#  2. COMPOSE_PROJECT_NAME namespaces networks + named volumes per customer.
cat > "${OUT_DIR}/docker-compose.override.yml" <<EOF
# Per-customer overrides for '${SLUG}'. Used together with the base production
# file. COMPOSE_PROJECT_NAME (set in .env below) namespaces volumes + networks;
# '!reset null' removes the base file's hardcoded container_name so multiple
# instances can coexist on one host without name collisions.
services:
  backend:
    container_name: !reset null
  worker:
    container_name: !reset null
  frontend:
    container_name: !reset null
  postgres:
    container_name: !reset null
  redis:
    container_name: !reset null
  backup-runner:
    container_name: !reset null
  backup-scheduler:
    container_name: !reset null
EOF

# Append the compose project name to the .env so `docker compose --env-file`
# picks it up for volume/network namespacing.
echo "" >> "${OUT_DIR}/.env"
echo "# Compose project name — namespaces this customer's containers/volumes/networks." >> "${OUT_DIR}/.env"
echo "COMPOSE_PROJECT_NAME=invenzo-${SLUG}" >> "${OUT_DIR}/.env"

# --- Caddy vhost snippet ----------------------------------------------------
cat > "${OUT_DIR}/Caddyfile.snippet" <<EOF
# --- Invenzo customer: ${SLUG} ---
# Add this block to /etc/caddy/Caddyfile, then: sudo systemctl reload caddy
${FQDN} {
    encode gzip

    @api path /api/* /health
    handle @api {
        reverse_proxy 127.0.0.1:${BACKEND_PORT}
    }

    handle {
        reverse_proxy 127.0.0.1:${FRONTEND_PORT}
    }
}
EOF

# --- per-customer README ----------------------------------------------------
cat > "${OUT_DIR}/README.md" <<EOF
# Invenzo instance: ${SLUG} (${FQDN})

Generated by \`scripts/provision_customer.sh\`. This directory holds this
customer's production config. \`.env\` contains real secrets and is gitignored.

## Ports on this host
- Backend:  127.0.0.1:${BACKEND_PORT}
- Frontend: 127.0.0.1:${FRONTEND_PORT}

## 1. DNS
Point \`${FQDN}\` at this server. With a wildcard \`*.${DOMAIN}\` A record already
in place, nothing to do. Otherwise add an A record: \`${SLUG}\` -> this server's IP.

## 2. Caddy
Append \`Caddyfile.snippet\` to \`/etc/caddy/Caddyfile\`, then:
\`\`\`bash
sudo systemctl reload caddy
\`\`\`

## 3. Bring the stack up (run from the repo root)
\`\`\`bash
docker compose --env-file customers/${SLUG}/.env \\
  -f docker-compose.production.yml \\
  -f customers/${SLUG}/docker-compose.override.yml \\
  up -d --build
\`\`\`
Migrations run automatically on backend startup. Grab the initial admin
temporary password (container name is prefixed with the project name):
\`\`\`bash
docker compose --env-file customers/${SLUG}/.env \\
  -f docker-compose.production.yml \\
  -f customers/${SLUG}/docker-compose.override.yml \\
  logs backend 2>&1 | grep "Temporary Password"
\`\`\`

## 4. Verify
\`\`\`bash
curl https://${FQDN}/health
\`\`\`
Then open https://${FQDN}, log in as \`admin\` with the temporary password, and
set a new password when prompted.

## 5. SMTP (optional but recommended) — Brevo free tier
Password-reset EMAILS require SMTP. Host/port/TLS are pre-filled for Brevo's
free relay. In Brevo -> Settings -> SMTP & API -> SMTP tab:
  - copy the **Login** into \`SMTP_USERNAME\` (e.g. \`1a2b3c001@smtp-brevo.com\`)
  - click **Generate SMTP key** and copy it into \`SMTP_PASSWORD\`
  - set \`SMTP_FROM_EMAIL\` to a sender you verified in Brevo
    (Senders, domains, IPs). Once \`${DOMAIN}\` is verified there, use
    \`no-reply@${DOMAIN}\`.
Then edit \`customers/${SLUG}/.env\` and re-run the up command.
(Admin-driven password reset in Settings works without SMTP.)

## Updating this instance later
\`\`\`bash
git pull
docker compose --env-file customers/${SLUG}/.env \\
  -f docker-compose.production.yml \\
  -f customers/${SLUG}/docker-compose.override.yml \\
  up -d --build
\`\`\`
EOF

echo "Provisioned customer '${SLUG}' -> ${FQDN}"
echo "  Directory:  customers/${SLUG}/"
echo "  Backend port:  ${BACKEND_PORT}   Frontend port: ${FRONTEND_PORT}"
echo "  Files: .env (SECRETS — gitignored), docker-compose.override.yml, Caddyfile.snippet, README.md"
echo ""
echo "Next: see customers/${SLUG}/README.md for DNS + Caddy + bring-up steps."
